language: node_js
os:
  - linux
  - osx
node_js:
  - "8.11.3"
  - "8"
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
cache:
  yarn: false
install:
  - yarn install
  - cd embark-ui && yarn install && cd ..
  - git status && test -z "$(git status --porcelain)"
script:
  - npm run build:node
  - npm test
